chore: set node version before yarn install

diff --git a/.devops/azure-templates/e2e-tests.yaml b/.devops/azure-templates/e2e-tests.yaml
--- a/.devops/azure-templates/e2e-tests.yaml
+++ b/.devops/azure-templates/e2e-tests.yaml
@@ -23,19 +23,22 @@ parameters:
       - PAYMENT
       - ONBOARDING
 
-resources:
-  repositories:
-    - repository: pagopaCommons
-      type: github
-      name: pagopa/azure-pipeline-templates
-      ref: refs/tags/v2.19
-      endpoint: 'io-azure-devops-github-ro'
 
 steps:
   - checkout: ${{parameters.CHECKOUT_RESOURCE_REPO_NAME}}
-  - template: templates/node-job-setup/template.yaml@pagopaCommons
-    parameters:
-      gitReference: ${{parameters.CHECKOUT_RESOURCE_REPO_NAME}}
+  - bash: |
+      echo "current folder: $(pwd)"
+      FROM_SOURCE=$(cat .node-version || cat .nvmrc)
+      ls .node-version && echo ".node-version found, value: '$(cat .node-version)'" || echo ".node-version not found"
+      ls .nvmrc && echo ".nvmrc found, value: '$(cat .nvmrc)'" || echo ".nvmrc not found"
+      echo "set FROM_SOURCE='$FROM_SOURCE'"
+      echo "##vso[task.setvariable variable=NODE_VERSION]$FROM_SOURCE"
+    workingDirectory: ${{ parameters.projectDir }}
+    displayName: 'Determine Node.js version from source'
+  - task: UseNode@1
+    inputs:
+      version: $(NODE_VERSION)
+    displayName: 'Set up Node.js'
   - script: |
       rm -f e2e-tests/.env && cp e2e-tests/dev.env e2e-tests/.env && sed -i "s/^USER_WALLET_TOKEN.*$/USER_WALLET_TOKEN=${{parameters.USER_WALLET_TOKEN_DEV}}/" e2e-tests/.env
     displayName: 'Set env for E2E test (DEV)'
